### PR TITLE
[Feature]Add proxy when use requests

### PR DESCRIPTION
**Pull request by TCCinTaiwan**
Issues #53

### CODE REVIEW

**Comment by mlouielu** [comment]
Can you add on unittest, with both http and [sock5](http://docs.python-requests.org/en/master/user/advanced/#socks) proxy?

**Comment by TCCinTaiwan** [comment]
I am not good at writing Python unit test now. If I have free time on holiday, I may study how to change it.

**Comment by mlouielu** [comment]
Sure, no problem, we can wait for it :)

**Comment by mlouielu** [comment]
Choice using #65

**Pull request closed without merging**
