### PR TITLE
Skip data with open "--" (fixed #27)

### LINKED ISSUE #27: 2017 12/18 大樹(6469) Error
2017 12/18 大樹(6469) ，當天無交易量，證交所的資料為 '--'
程式會出現 Error。

希望能自動拿前一天的收盤價取代表示。

### PR DESCRIPTION
**Pull request by ianlini**
I just use the same method in `TWSEFetcher`

### CODE REVIEW

**Comment by ianlini** [comment]
fixed #27

**Comment by mlouielu** [comment]
Should we use `0` or just skip the data?

**Comment by ianlini** [comment]
As I mentioned in #27, I think the better way is to replace the `--` with `None` and let users deal with them.
If you agree with this, I can implement this when I find some time.
In the future, you may also provide some filling methods to let users choose (like in Pandas).

**Comment by mlouielu** [comment]
OK, let's just make it as `None` if the data shows up with `'--'`. Do you agree with that?

**Comment by ianlini** [comment]
Yes. I will then send another PR for this.

**Pull request closed without merging**
